FROM golang:1.19.1 AS builder

### Get Go code
WORKDIR /src/
COPY . .

### Build the executabless
RUN go build -o /app/webapi ./cmd/webapi

### Final container
FROM debian:bullseye

### Port
EXPOSE 3000 4000

### Copy of the executable from builder image
WORKDIR /app/
COPY --from=builder /app/webapi ./

### Executable command
CMD ["/app/webapi"]