FROM node:lts as builder

### Get Vue.js code
WORKDIR /app
COPY webui webui

### Build Vue.js into HTML/CSS/JS
WORKDIR /app/webui
RUN npm run build-prod


### Make final container
FROM nginx:stable

### Get the  app from the builder image
COPY --from=builder /app/webui/dist /usr/share/nginx/html

